// Package turnkeycustody adapts Turnkey's transaction-aware API to the
// signer-owned Jupiter custody boundary. It does not submit transactions.
package turnkeycustody

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/hex"
	"errors"
	"io"
	"log"
	"net/http"
	"strconv"
	"strings"
	"time"
	"unicode"

	"github.com/Overclock-Validator/mithril-agent/internal/securefile"
	"github.com/Overclock-Validator/mithril-agent/signer"
	"github.com/Overclock-Validator/mithril-agent/solana"
	turnkey "github.com/tkhq/go-sdk/v2"
)

const (
	maxIdentifierBytes       = 256
	maxResponseBytes         = 1 << 20
	maxSolanaTransactionSize = 1232
	maximumAPIKeyBytes       = 512
	requestTimeout           = 20 * time.Second
	turnkeyAPIOrigin         = "https://api.turnkey.com"
)

var (
	errResponseTooLarge = errors.New("Turnkey custody response exceeds its size limit")
	errSigningRefused   = errors.New("Turnkey custody signing was refused")
)

type Config struct {
	OrganizationID string
	SignWith       string
}

type turnkeyIdentityClient interface {
	GetWhoami(context.Context, turnkey.GetWhoamiRequest) (*turnkey.GetWhoamiResponse, error)
	GetPrivateKey(context.Context, turnkey.GetPrivateKeyRequest) (*turnkey.GetPrivateKeyResponse, error)
	GetPrivateKeys(context.Context, turnkey.GetPrivateKeysRequest) (*turnkey.GetPrivateKeysResponse, error)
	GetWalletAccount(context.Context, turnkey.GetWalletAccountRequest) (*turnkey.GetWalletAccountResponse, error)
	GetWallets(context.Context, turnkey.GetWalletsRequest) (*turnkey.GetWalletsResponse, error)
}

// NewVerifiedFromAPIKeyFile creates the fixed transaction-only signer only
// after authenticating the API identity and proving that SignWith resolves to
// the expected Solana address. It performs no signing activity.
func NewVerifiedFromAPIKeyFile(
	ctx context.Context,
	path, publicKey string,
	config Config,
	expectedAddress string,
) (*Signer, error) {
	if ctx == nil || ctx.Err() != nil {
		return nil, errors.New("Turnkey custody verification was canceled")
	}
	if err := validateConfig(config); err != nil {
		return nil, err
	}
	if _, err := solana.Decode32(expectedAddress); err != nil {
		return nil, errors.New("Turnkey expected Solana address is invalid")
	}
	stamper, err := loadVerifiedAPIKeyStamper(path, publicKey)
	if err != nil {
		return nil, err
	}
	client, err := newTurnkeyClient(stamper, config.OrganizationID)
	if err != nil {
		return nil, err
	}
	requestCtx, cancel := context.WithTimeout(ctx, requestTimeout)
	defer cancel()
	if err := verifyTurnkeySigningAddress(
		requestCtx, client, config.OrganizationID, config.SignWith, expectedAddress,
	); err != nil {
		if requestCtx.Err() != nil {
			return nil, errors.New("Turnkey custody verification timed out or was canceled")
		}
		return nil, err
	}
	return newSigner(client, config)
}

func loadVerifiedAPIKeyStamper(path, publicKey string) (*turnkey.APIKeyStamper, error) {
	stamper, err := loadAPIKeyStamper(path)
	if err != nil {
		return nil, err
	}
	if publicKey == "" {
		return nil, errors.New("Turnkey API public key is required for local key-pair verification")
	}
	if stamper.PublicKey() != publicKey {
		return nil, errors.New("Turnkey API private key does not match the configured public key; use the .private and .public files from the same Turnkey CLI generation")
	}
	return stamper, nil
}

func loadAPIKeyStamper(path string) (*turnkey.APIKeyStamper, error) {
	data, err := securefile.ReadPrivate(path, maximumAPIKeyBytes)
	if err != nil {
		return nil, errors.New("Turnkey API private-key file could not be read safely; use the mode-0600 .private file generated by Turnkey CLI, not a dashboard activity JSON")
	}
	defer clear(data)
	privateKey := strings.TrimSuffix(strings.TrimSpace(string(data)), ":p256")
	decoded, err := hex.DecodeString(privateKey)
	if err != nil || len(decoded) != 32 || strings.ContainsAny(privateKey, " \t\r\n") {
		return nil, errors.New("Turnkey API private-key file is invalid; use the matching .private file generated by Turnkey CLI, not a dashboard activity JSON")
	}
	clear(decoded)
	stamper, err := turnkey.NewAPIKeyStamper(privateKey)
	if err != nil {
		return nil, errors.New("Turnkey API private-key file is invalid; use the matching .private file generated by Turnkey CLI, not a dashboard activity JSON")
	}
	return stamper, nil
}

type transactionClient interface {
	SignTransaction(context.Context, turnkey.SignTransactionRequest) (*turnkey.SignTransactionResponse, error)
}

type Signer struct {
	client         transactionClient
	organizationID string
	signWith       string
}

func newWithStamper(stamper turnkey.Stamper, config Config) (*Signer, error) {
	if stamper == nil {
		return nil, errors.New("Turnkey API stamper is unavailable")
	}
	if err := validateConfig(config); err != nil {
		return nil, err
	}
	client, err := newTurnkeyClient(stamper, config.OrganizationID)
	if err != nil {
		return nil, err
	}
	return newSigner(client, config)
}

func newTurnkeyClient(stamper turnkey.Stamper, organizationID string) (*turnkey.Client, error) {
	client, err := turnkey.NewClient(
		stamper,
		organizationID,
		turnkey.WithHTTPClient(secureHTTPClient(turnkeyAPIOrigin)),
		turnkey.WithHTTPRetries(1),
		turnkey.WithHTTPRetryDelay(100*time.Millisecond),
		turnkey.WithActivityPollInterval(250*time.Millisecond),
		turnkey.WithActivityPollTimeout(requestTimeout),
		turnkey.WithLogger(log.New(io.Discard, "", 0)),
	)
	if err != nil {
		return nil, errors.New("Turnkey custody client could not be initialized")
	}
	return client, nil
}

func verifyTurnkeySigningAddress(
	ctx context.Context,
	client turnkeyIdentityClient,
	organizationID, privateKeyID, expectedAddress string,
) error {
	whoami, err := client.GetWhoami(ctx, turnkey.GetWhoamiRequest{
		OrganizationID: organizationID,
	})
	if err != nil || whoami == nil || whoami.OrganizationID != organizationID {
		return errors.New("Turnkey API identity could not be authenticated; register the matching public key with the dedicated API-only user in the configured organization")
	}
	if privateKeyID == expectedAddress {
		response, err := client.GetPrivateKeys(ctx, turnkey.GetPrivateKeysRequest{
			OrganizationID: organizationID,
		})
		if err == nil && response != nil {
			for _, privateKey := range response.PrivateKeys {
				if hasTurnkeySolanaAddress(privateKey.Addresses, expectedAddress) {
					return nil
				}
			}
		}
		wallets, err := client.GetWallets(ctx, turnkey.GetWalletsRequest{
			OrganizationID: organizationID,
		})
		if err != nil || wallets == nil {
			return errors.New("Turnkey signing-address mapping could not be read")
		}
		for _, wallet := range wallets.Wallets {
			account, err := client.GetWalletAccount(ctx, turnkey.GetWalletAccountRequest{
				Address:        &expectedAddress,
				OrganizationID: organizationID,
				WalletID:       wallet.WalletID,
			})
			if err == nil && account != nil &&
				account.Account.Address == expectedAddress &&
				account.Account.AddressFormat == turnkey.AddressFormatSolana &&
				account.Account.Curve == turnkey.CurveEd25519 {
				return nil
			}
		}
		return errors.New("Turnkey signing address does not belong to the configured organization")
	}
	response, err := client.GetPrivateKey(ctx, turnkey.GetPrivateKeyRequest{
		OrganizationID: organizationID,
		PrivateKeyID:   privateKeyID,
	})
	if err != nil || response == nil {
		return errors.New("Turnkey private-key mapping could not be read")
	}
	if hasTurnkeySolanaAddress(response.PrivateKey.Addresses, expectedAddress) {
		return nil
	}
	return errors.New("Turnkey private-key ID belongs to a different Solana address")
}

func hasTurnkeySolanaAddress(addresses []turnkey.ExternalDataV1Address, expected string) bool {
	for _, address := range addresses {
		if address.Format != nil && *address.Format == turnkey.AddressFormatSolana &&
			address.Address != nil && *address.Address == expected {
			return true
		}
	}
	return false
}

func newSigner(client transactionClient, config Config) (*Signer, error) {
	if client == nil {
		return nil, errors.New("Turnkey custody client is unavailable")
	}
	if err := validateConfig(config); err != nil {
		return nil, err
	}
	return &Signer{
		client: client, organizationID: config.OrganizationID, signWith: config.SignWith,
	}, nil
}

// Sign signs only the exact canonical transaction and stable timestamp that
// the signer authorization ledger made durable before calling custody.
func (s *Signer) Sign(
	ctx context.Context,
	request signer.TransactionCustodyRequest,
) ([]byte, error) {
	if s == nil || s.client == nil {
		return nil, errors.New("Turnkey custody signer is unavailable")
	}
	if ctx == nil {
		return nil, errors.New("Turnkey custody context is unavailable")
	}
	if ctx.Err() != nil {
		return nil, errors.New("Turnkey custody signing was canceled")
	}
	if err := validateRequest(request); err != nil {
		return nil, err
	}
	unsignedHex := hex.EncodeToString(request.Transaction)
	input := turnkey.SignTransactionRequest{
		OrganizationID:      s.organizationID,
		TimestampMs:         strconv.FormatInt(request.TimestampMS, 10),
		SignWith:            s.signWith,
		TypeValue:           turnkey.TransactionTypeSolana,
		UnsignedTransaction: unsignedHex,
	}

	requestCtx, cancel := context.WithTimeout(ctx, requestTimeout)
	defer cancel()
	response, err := s.client.SignTransaction(requestCtx, input)
	if requestCtx.Err() != nil {
		if errors.Is(requestCtx.Err(), context.DeadlineExceeded) {
			return nil, errors.New("Turnkey custody signing timed out")
		}
		return nil, errors.New("Turnkey custody signing was canceled")
	}
	if err != nil {
		var requestError *turnkey.RequestError
		if errors.As(err, &requestError) {
			switch {
			case requestError.StatusCode == http.StatusTooManyRequests:
				return nil, errors.New("Turnkey custody is rate or plan limited; retry after the provider window resets or check the account signature allowance")
			case requestError.StatusCode >= http.StatusInternalServerError:
				return nil, errors.New("Turnkey custody is temporarily unavailable")
			}
		}
		var approval *turnkey.ActivityRequiresApprovalError
		if errors.As(err, &approval) {
			return nil, errors.New("Turnkey custody signing requires approval; use a dedicated non-root API-only user with an exact allow policy")
		}
		var failed *turnkey.ActivityFailedError
		if errors.As(err, &failed) && failed.Status == turnkey.ActivityStatusRejected {
			return nil, errSigningRefused
		}
		return nil, errors.New("Turnkey custody signing failed")
	}
	if !validResponse(response, input) {
		return nil, errors.New("Turnkey custody response did not match the request")
	}
	signed, err := hex.DecodeString(response.SignedTransaction)
	if err != nil || len(signed) != len(request.Transaction) {
		return nil, errors.New("Turnkey custody response did not contain a valid Solana transaction")
	}
	envelope, err := solana.VerifySignedTransactionEnvelope(signed)
	if err != nil || envelope.Version != 0 || !bytes.Equal(envelope.Message, request.Transaction[65:]) {
		return nil, errors.New("Turnkey custody response did not contain a valid Solana transaction")
	}
	return signed, nil
}

// IsSigningRefused distinguishes a terminal provider-side activity refusal
// from a transport or availability failure without exposing provider details.
func IsSigningRefused(err error) bool {
	return errors.Is(err, errSigningRefused)
}

func validateConfig(config Config) error {
	if !validIdentifier(config.OrganizationID) || !validIdentifier(config.SignWith) {
		return errors.New("Turnkey custody configuration is invalid")
	}
	return nil
}

func validIdentifier(value string) bool {
	if value == "" || len(value) > maxIdentifierBytes || strings.TrimSpace(value) != value {
		return false
	}
	return !strings.ContainsFunc(value, unicode.IsControl)
}

func validateRequest(request signer.TransactionCustodyRequest) error {
	digest, err := hex.DecodeString(request.RequestSHA256)
	if err != nil || len(digest) != 32 || hex.EncodeToString(digest) != request.RequestSHA256 ||
		request.TimestampMS <= 0 || len(request.Transaction) < 66 ||
		len(request.Transaction) > maxSolanaTransactionSize || request.Transaction[0] != 1 ||
		!bytes.Equal(request.Transaction[1:65], make([]byte, 64)) || request.Transaction[65]&0x80 == 0 {
		return errors.New("Turnkey custody request is invalid")
	}
	return nil
}

func validResponse(response *turnkey.SignTransactionResponse, request turnkey.SignTransactionRequest) bool {
	if response == nil || response.Activity.Status != turnkey.ActivityStatusCompleted ||
		response.Activity.TypeValue != turnkey.ActivityTypeSignTransactionV2 ||
		response.Activity.OrganizationID != request.OrganizationID ||
		response.Activity.Intent.SignTransactionIntentV2 == nil {
		return false
	}
	intent := response.Activity.Intent.SignTransactionIntentV2
	return intent.SignWith == request.SignWith && intent.TypeValue == request.TypeValue &&
		intent.UnsignedTransaction == request.UnsignedTransaction && response.SignedTransaction != ""
}

func secureHTTPClient(origin string) *http.Client {
	defaultTransport, ok := http.DefaultTransport.(*http.Transport)
	if !ok {
		defaultTransport = &http.Transport{Proxy: http.ProxyFromEnvironment}
	}
	transport := defaultTransport.Clone()
	transport.Proxy = nil
	if transport.TLSClientConfig == nil {
		transport.TLSClientConfig = &tls.Config{MinVersion: tls.VersionTLS12}
	} else {
		transport.TLSClientConfig = transport.TLSClientConfig.Clone()
		transport.TLSClientConfig.MinVersion = tls.VersionTLS12
	}
	return &http.Client{
		Transport: &boundedTransport{
			base: transport, origin: strings.TrimRight(origin, "/"),
		},
		Timeout:       requestTimeout,
		CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse },
	}
}

type boundedTransport struct {
	base   http.RoundTripper
	origin string
}

func (transport *boundedTransport) RoundTrip(request *http.Request) (*http.Response, error) {
	if request.URL.Scheme+"://"+request.URL.Host != transport.origin {
		return nil, errors.New("Turnkey custody transport refused an unexpected origin")
	}
	response, err := transport.base.RoundTrip(request)
	if err != nil {
		return nil, err
	}
	if response.ContentLength > maxResponseBytes {
		_ = response.Body.Close()
		return nil, errResponseTooLarge
	}
	response.Body = &boundedReadCloser{body: response.Body, remaining: maxResponseBytes}
	return response, nil
}

type boundedReadCloser struct {
	body      io.ReadCloser
	remaining int64
}

func (reader *boundedReadCloser) Read(buffer []byte) (int, error) {
	if reader.remaining == 0 {
		var extra [1]byte
		if count, err := reader.body.Read(extra[:]); count != 0 {
			return 0, errResponseTooLarge
		} else {
			return 0, err
		}
	}
	if int64(len(buffer)) > reader.remaining {
		buffer = buffer[:reader.remaining]
	}
	count, err := reader.body.Read(buffer)
	reader.remaining -= int64(count)
	return count, err
}

func (reader *boundedReadCloser) Close() error {
	return reader.body.Close()
}
